
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\63947\Documents\College\DBMS PROJECT\Main_Win\assets\main_win_img")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


main_window = Tk()

main_window.geometry("1200x700")
main_window.configure(bg = "#D9D9D9")


canvas = Canvas(
    main_window,
    bg = "#D9D9D9",
    height = 700,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    76.0,
    221.0,
    1121.00048828125,
    223.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    1200.0,
    202.0,
    fill="#4C0C7E",
    outline="")

canvas.create_rectangle(
    44.0,
    30.0,
    179.0,
    165.0,
    fill="#FFFFFF",
    outline="")

main_docex_logo_image = PhotoImage(
    file=relative_to_assets("main_docex_logo.png"))
main_docex_logo = canvas.create_image(
    1107.0,
    54.0,
    image=main_docex_logo_image
)

canvas.create_text(
    853.0,
    227.0,
    anchor="nw",
    text="Image",
    fill="#000000",
    font=("Inter SemiBold", 17 * -1)
)

canvas.create_text(
    524.0,
    227.0,
    anchor="nw",
    text="Expiration Date",
    fill="#000000",
    font=("Inter SemiBold", 17 * -1)
)

canvas.create_text(
    138.0,
    227.0,
    anchor="nw",
    text="Type of Document/ID",
    fill="#000000",
    font=("Inter SemiBold", 17 * -1)
)
#--------------------------------------------------------------------------------------------------------------------
#Search
def on_enter(e):
    Search.delete(0,'end')
def on_leave(e):
    Username=Username.get()
    if Search == '':
        Search.insert(0,"Username")
Search = Entry(main_window, width=25, fg='black',border=0,bg='white',font=('Microsoft YaHei UI Light',15))
Search.place(x=340.0,y=135.0,)
Search.insert(0,'Search')
Search.bind('<FocusIn>',on_enter)
Search.bind('<FocusOut>',on_leave)
#--------------------------------------------------------------------------------------------------------------------
rectangle_image = PhotoImage(
    file=relative_to_assets("rectangle.png"))
rectangle = canvas.create_image(
    600.0,
    370.0,
    image=rectangle_image
)

main_dlt_btn_image = PhotoImage(
    file=relative_to_assets("main_dlt_btn.png"))
main_dlt_btn = Button(
    image=main_dlt_btn_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
main_dlt_btn.place(
    x=757.0,
    y=634.0,
    width=210.0,
    height=40.0
)

main_edit_btn_image = PhotoImage(
    file=relative_to_assets("main_edit_btn.png"))
main_edit_btn = Button(
    image=main_edit_btn_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
main_edit_btn.place(
    x=495.0,
    y=633.0,
    width=210.0,
    height=40.0
)

main_add_btn_image = PhotoImage(
    file=relative_to_assets("main_add_btn.png"))
main_add_btn = Button(
    image=main_add_btn_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
main_add_btn.place(
    x=233.0,
    y=634.0,
    width=210.0,
    height=40.0
)

main_search_btn_image = PhotoImage(
    file=relative_to_assets("main_search_btn.png"))
main_search_btn = Button(
    image=main_search_btn_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
main_search_btn.place(
    x=884.0,
    y=130.0,
    width=40.0,
    height=40.0
)
main_window.resizable(False, False)
main_window.mainloop()
